version: '3.9'

services:
  db:
    image: postgres:alpine3.18
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    container_name: avito_db
    networks:
      - avito_net

  redis:
    image: redis:alpine3.17
    restart: unless-stopped
    container_name: avito_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - avito_net

  app:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - avito_net

  swagger:
    image: swaggerapi/swagger-ui:v4.0.0-rc.1
    container_name: swagger
    ports:
      - "8081:8080"
    depends_on:
      - app
    volumes:
      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml
    environment:
      - URL=http://localhost:8081/openapi.yaml
    networks:
      - avito_net

networks:
  avito_net:
