app:
  # TODO change host to "app"
  host: "localhost"
  port: "8080"

db:
  user: "postgres"
  # TODO change host to "db"
  host: "localhost"
  # TODO change port
  port: "5433"
  name: "avito"
  password: "password"

redis:
  # TODO change host to "redis"
  host: "localhost"
  # TODO change port
  port: "6380"
