// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mock_history is a generated GoMock package.
package mock_history

import (
	context "context"
	history "main/internal/history"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v4"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, history *history.History, tx pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, history, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, history, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, history, tx)
}

// GetFromDate mocks base method.
func (m *MockRepository) GetFromDate(ctx context.Context, date time.Time) ([]history.HistoryDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromDate", ctx, date)
	ret0, _ := ret[0].([]history.HistoryDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromDate indicates an expected call of GetFromDate.
func (mr *MockRepositoryMockRecorder) GetFromDate(ctx, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromDate", reflect.TypeOf((*MockRepository)(nil).GetFromDate), ctx, date)
}
